name: Build

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Đảm bảo clone toàn bộ lịch sử cho phân tích chính xác

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node

      - name: Install dependencies and build
        run: |
          npm install
          npm run build  # Thay bằng lệnh build thực tế của dự án nếu cần

      - name: Analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          npx sonar-scanner \
          -Dsonar.projectKey=test1 \
          -Dsonar.projectName='test1' \
          -Dsonar.sources=src
