name: CI/CD with SonarQube and Jenkins

on:
  push:
    branches:
      - dev
      - staging
      - main

jobs:
  code-analysis:
    name: Code Analysis with SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install Sonar Scanner
        run: |
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
          unzip sonar-scanner-cli-4.7.0.2747-linux.zip
          mv sonar-scanner-4.7.0.2747-linux sonar-scanner
          export PATH=$PATH:$(pwd)/sonar-scanner/bin
          echo $PATH
          sonar-scanner --version

      - name: Run SonarQube Analysis
        run: |
          export PATH=$PATH:$(pwd)/sonar-scanner/bin
          sonar-scanner \
            -Dsonar.projectKey=react-native-web \
            -Dsonar.sources=. \
            -Dsonar.host.url=http://34.170.74.189:9000 \
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}

  trigger-jenkins:
    name: Trigger Jenkins CI/CD
    needs: code-analysis
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Pipeline
        uses: appleboy/jenkins-action@v1.4.0
        with:
          jenkins_url: ${{ secrets.JENKINS_URL }}
          username: ${{ secrets.JENKINS_USER }}
          password: ${{ secrets.JENKINS_TOKEN }}
          job: 'react-native-web-ci-cd'
          parameters: '{"branch": "${{ github.ref_name }}"}'
