name: Check Changes and Trigger Jenkins Deployment

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  trigger-jenkins:
    name: Trigger Jenkins Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Determine Branch and Deploy Environment
        id: set-env
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [ "$BRANCH_NAME" == "main" ]; then
            echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" == "dev" ]; then
            echo "DEPLOY_ENV=dev" >> $GITHUB_ENV
          elif [ "$BRANCH_NAME" == "staging" ]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          else
            echo "Branch $BRANCH_NAME is not configured for deployment."
            exit 1
        env:
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Trigger Jenkins Job
        run: |
          curl -X POST "http://your-jenkins-url/job/your-job-name/buildWithParameters" \
            --data-urlencode "token=your-trigger-token" \
            --data-urlencode "BRANCH_NAME=${{ github.ref_name }}" \
            --data-urlencode "DEPLOY_ENV=${{ env.DEPLOY_ENV }}"
