name: Trigger Jenkins Job on Dev, Main, and Staging Branches

on:
  push:
    branches:
      - dev         # Kích hoạt khi có thay đổi trên nhánh dev
      - main        # Kích hoạt khi có thay đổi trên nhánh main
      - staging     # Kích hoạt khi có thay đổi trên nhánh staging

jobs:
  trigger-jenkins:
    name: Trigger Jenkins Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Trigger Jenkins Job Remotely
        run: |
          echo "Triggering Jenkins Job for Branch: ${{ github.ref_name }}"
          
          # Kiểm tra nhánh hiện tại và trigger Jenkins job tương ứng
          if [ "${{ github.ref_name }}" = "main" ]; then
            curl -X POST "${{ secrets.JENKINS_URL }}/job/pipeline-main/buildWithParameters" \
              --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
              --data-urlencode "BRANCH=main"
          elif [ "${{ github.ref_name }}" = "staging" ]; then
            curl -X POST "${{ secrets.JENKINS_URL }}/job/pipeline-staging/buildWithParameters" \
              --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
              --data-urlencode "BRANCH=staging"
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            curl -X POST "${{ secrets.JENKINS_URL }}/job/pipeline-dev/buildWithParameters" \
              --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_API_TOKEN }}" \
              --data-urlencode "BRANCH=dev"
          else
            echo "Branch ${{ github.ref_name }} is not handled by this workflow."
          fi
