name: Build and Analyze React App

on:
  push:
    branches:
      - dev  # Chạy workflow khi có thay đổi được đẩy lên nhánh "dev"

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Test connection to SonarQube
        run: |
          curl -v http://34.170.74.189:9000  # Kiểm tra kết nối tới SonarQube

      - name: Analyze code with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}  # Token của SonarQube
        run: |
          npx sonar-scanner -X \
          -Dsonar.projectKey=test1 \
          -Dsonar.projectName="test1" \
          -Dsonar.sources=src \
          -Dsonar.exclusions=**/node_modules/**,**/build/** \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.host.url=http://34.170.74.189:9000 
